using System.Collections.Generic;

namespace NecnatAbp.Br.GeGeocodificacao
{
    public static partial class LogradouroConsts
    {
        public const int MaxCepLength = 8;
        public const int MaxNomeLength = 256;
        public const int MaxNomeAbreviadoLength = 128;
        public const int MaxComplementoLength = 512;

        public static readonly Dictionary<string, string> DictionaryLogradouroTipoAbreviatura =
            new Dictionary<string, string>
            {
                { "ACA", "Acampamento" },
                { "AC", "Acesso" },
                { "ACL", "Acesso Local" },
                { "AD", "Adro" },
                { "AER", "Aeroporto" },
                { "AL", "Alameda" },
                { "AT", "Alto" },
                { "AN", "Anel Viário" },
                { "ANT", "Antiga Estrada" },
                { "A", "Área" },
                { "AE", "Área Especial" },
                { "A V", "Área Verde" },
                { "ART", "Artéria" },
                { "ATL", "Atalho" },
                { "AV", "Avenida" },
                { "AVC", "Avenida Contorno" },
                { "AVM", "Avenida Marginal" },
                { "AMD", "Avenida Marginal Direita" },
                { "AME", "Avenida Marginal Esquerda" },
                { "AVV", "Avenida Velha" },
                { "BX", "Baixa" },
                { "BLO", "Balão" },
                { "BAL", "Balneário" },
                { "BC", "Beco" },
                { "BEL", "Belvedere" },
                { "BL", "Bloco" },
                { "BLS", "Blocos" },
                { "BSQ", "Bosque" },
                { "BVD", "Boulevard" },
                { "BLV", "Bulevar" },
                { "BCO", "Buraco" },
                { "C", "Cais" },
                { "CAL", "Calçada" },
                { "CAM", "Caminho" },
                { "CPO", "Campo" },
                { "CAN", "Canal" },
                { "CH", "Chácara" },
                { "CHA", "Chapadão" },
                { "CIC", "Ciclovia" },
                { "CIR", "Circular" },
                { "COL", "Colônia" },
                { "CMP", "Complexo Viário" },
                { "COM", "Comunidade" },
                { "CON", "Condomínio" },
                { "CJ", "Conjunto" },
                { "CJM", "Conjunto Mutirão" },
                { "CTN", "Contorno" },
                { "COR", "Corredor" },
                { "CRG", "Córrego" },
                { "DSC", "Descida" },
                { "DSV", "Desvio" },
                { "DT", "Distrito" },
                { "EX", "Eixo Industrial" },
                { "EVD", "Elevada" },
                { "ENS", "Enseada" },
                { "ENT", "Entrada Particular" },
                { "EB", "Entre Bloco" },
                { "EQ", "Entre Quadra" },
                { "ESC", "Escada" },
                { "ESD", "Escadaria" },
                { "ESP", "Esplanada" },
                { "ETC", "Estação" },
                { "ETT", "Estacionamento" },
                { "ETD", "Estádio" },
                { "ETN", "Estância" },
                { "EST", "Estrada" },
                { "ETA", "Estrada Antiga" },
                { "ESL", "Estrada de Ligação" },
                { "ESS", "Estrada de Servidão" },
                { "ESE", "Estrada Estadual" },
                { "EIM", "Estrada Intermunicipal" },
                { "ESM", "Estrada Municipal" },
                { "ETP", "Estrada Particular" },
                { "ESV", "Estrada Velha" },
                { "ESI", "Estrada Vicinal" },
                { "EVA", "Evangélica" },
                { "FAV", "Favela" },
                { "FAZ", "Fazenda" },
                { "FRA", "Feira" },
                { "FER", "Ferrovia" },
                { "FNT", "Fonte" },
                { "FTE", "Forte" },
                { "GAL", "Galeria" },
                { "GJA", "Granja" },
                { "IA", "Ilha" },
                { "IOA", "Ilhota" },
                { "IND", "Indeterminado" },
                { "JD", "Jardim" },
                { "JDE", "Jardinete" },
                { "LD", "Ladeira" },
                { "LGO", "Lago" },
                { "LGA", "Lagoa" },
                { "LRG", "Largo" },
                { "LT", "Lote" },
                { "LOT", "Loteamento" },
                { "RPR", "Margem" },
                { "MNA", "Marina" },
                { "MER", "Mercado" },
                { "MOD", "Modulo" },
                { "MTE", "Monte" },
                { "MRO", "Morro" },
                { "NUC", "Núcleo" },
                { "HAB", "Núcleo Habitacional" },
                { "NUR", "Núcleo Rural" },
                { "OUT", "Outeiro" },
                { "PDA", "Parada" },
                { "PDO", "Paradouro" },
                { "PAR", "Paralela" },
                { "PRQ", "Parque" },
                { "PRM", "Parque Municipal" },
                { "PRR", "Parque Residencial" },
                { "PSG", "Passagem" },
                { "PSP", "Passagem de Pedestre" },
                { "PSS", "Passagem Subterrânea" },
                { "PSA", "Passarela" },
                { "PAS", "Passeio" },
                { "PAT", "Pátio" },
                { "PNT", "Ponta" },
                { "PTE", "Ponte" },
                { "PTO", "Porto" },
                { "PC", "Praça" },
                { "PCE", "Praça de Esportes" },
                { "PR", "Praia" },
                { "MRG", "Projeção" },
                { "PRL", "Prolongamento" },
                { "Q", "Quadra" },
                { "QTA", "Quinta" },
                { "QTS", "Quintas" },
                { "RAM", "Ramal" },
                { "RMP", "Rampa" },
                { "REC", "Recanto" },
                { "RCR", "Recreio" },
                { "RES", "Residencial" },
                { "RET", "Reta" },
                { "RER", "Retiro" },
                { "RTN", "Retorno" },
                { "ROA", "Rodo Anel" },
                { "ROD", "Rodovia" },
                { "RTT", "Rotatória" },
                { "ROT", "Rotula" },
                { "R", "Rua" },
                { "R L", "Rua de Ligação" },
                { "RPE", "Rua de Pedestre" },
                { "R I", "Rua Integração" },
                { "R P", "Rua Particular" },
                { "R V", "Rua Velha" },
                { "RLA", "Ruela" },
                { "SEG", "Segunda Avenida" },
                { "SRV", "Servidão" },
                { "ST", "Setor" },
                { "SIT", "Sitio" },
                { "SUB", "Subida" },
                { "TER", "Terminal" },
                { "TV", "Travessa" },
                { "TVP", "Travessa Particular" },
                { "TVV", "Travessa Velha" },
                { "TR", "Trecho" },
                { "TRV", "Trevo" },
                { "TCH", "Trincheira" },
                { "TUN", "Túnel" },
                { "UNI", "Unidade" },
                { "VAL", "Vala" },
                { "VLE", "Vale" },
                { "VRT", "Variante" },
                { "VER", "Vereda" },
                { "V", "Via" },
                { "V C", "Via Coletora" },
                { "VCO", "Via Costeira" },
                { "VAC", "Via de Acesso" },
                { "VPE", "Via de Pedestre" },
                { "VEV", "Via Elevado" },
                { "V-E", "Via Expressa" },
                { "VLT", "Via Litorânea" },
                { "V L", "Via Local" },
                { "VD", "Viaduto" },
                { "VLA", "Viela" },
                { "VL", "Vila" },
                { "ZIG", "Zigue-Zague" }
            };
    }
}
